In [5]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

In [7]:
df=pd.read_csv('emails.csv')
df

Email No.  the  to  ect  and  for  of    a  you  hou  ...  connevey  \
0        Email 1    0   0    1    0    0   0    2    0    0  ...         0   
1        Email 2    8  13   24    6    6   2  102    1   27  ...         0   
2        Email 3    0   0    1    0    0   0    8    0    0  ...         0   
3        Email 4    0   5   22    0    5   1   51    2   10  ...         0   
4        Email 5    7   6   17    1    5   2   57    0    9  ...         0   
...          ...  ...  ..  ...  ...  ...  ..  ...  ...  ...  ...       ...   
5167  Email 5168    2   2    2    3    0   0   32    0    0  ...         0   
5168  Email 5169   35  27   11    2    6   5  151    4    3  ...         0   
5169  Email 5170    0   0    1    1    0   0   11    0    0  ...         0   
5170  Email 5171    2   7    1    0    2   1   28    2    0  ...         0   
5171  Email 5172   22  24    5    1    6   5  148    8    2  ...         0   

      jay  valued  lay  infrastructure  military  allowing  ff  dry  \
0       0       0    0               0         0         0   0    0   
1       0       0    0               0         0         0   1    0   
2       0       0    0               0         0         0   0    0   
3       0       0    0               0         0         0   0    0   
4       0       0    0               0         0         0   1    0   
...   ...     ...  ...             ...       ...       ...  ..  ...   
5167    0       0    0               0         0         0   0    0   
5168    0       0    0               0         0         0   1    0   
5169    0       0    0               0         0         0   0    0   
5170    0       0    0               0         0         0   1    0   
5171    0       0    0               0         0         0   0    0   

      Prediction  
0              0  
1              0  
2              0  
3              0  
4              0  
...          ...  
5167           0  
5168           0  
5169           1  
5170           1  
5171           0  

[5172 rows x 3002 columns]

In [9]:
X=df.drop(columns=['Email No.','Prediction'])
X

the  to  ect  and  for  of    a  you  hou  in  ...  enhancements  \
0       0   0    1    0    0   0    2    0    0   0  ...             0   
1       8  13   24    6    6   2  102    1   27  18  ...             0   
2       0   0    1    0    0   0    8    0    0   4  ...             0   
3       0   5   22    0    5   1   51    2   10   1  ...             0   
4       7   6   17    1    5   2   57    0    9   3  ...             0   
...   ...  ..  ...  ...  ...  ..  ...  ...  ...  ..  ...           ...   
5167    2   2    2    3    0   0   32    0    0   5  ...             0   
5168   35  27   11    2    6   5  151    4    3  23  ...             0   
5169    0   0    1    1    0   0   11    0    0   1  ...             0   
5170    2   7    1    0    2   1   28    2    0   8  ...             0   
5171   22  24    5    1    6   5  148    8    2  23  ...             0   

      connevey  jay  valued  lay  infrastructure  military  allowing  ff  dry  
0            0    0       0    0               0         0         0   0    0  
1            0    0       0    0               0         0         0   1    0  
2            0    0       0    0               0         0         0   0    0  
3            0    0       0    0               0         0         0   0    0  
4            0    0       0    0               0         0         0   1    0  
...        ...  ...     ...  ...             ...       ...       ...  ..  ...  
5167         0    0       0    0               0         0         0   0    0  
5168         0    0       0    0               0         0         0   1    0  
5169         0    0       0    0               0         0         0   0    0  
5170         0    0       0    0               0         0         0   1    0  
5171         0    0       0    0               0         0         0   0    0  

[5172 rows x 3000 columns]

In [14]:
Y=df.iloc[:,-1]
Y

0       0
1       0
2       0
3       0
4       0
       ..
5167    0
5168    0
5169    1
5170    1
5171    0
Name: Prediction, Length: 5172, dtype: int64

In [15]:
x_train, x_test, y_train, y_test=train_test_split(X,Y,test_size=0.20,random_state=8)

In [18]:
def apply_model(model):
    model.fit(x_train,y_train)
    print("Model Train Score",model.score(x_train,y_train))
    print("Model Test Score",model.score(x_test,y_test))
    print("Accuracy",model.score (x_test,y_test))
    y_pred=model.predict(x_test)
    print("Predictions",y_pred)
    print("Confusion Matrix: \n", confusion_matrix(y_test,y_pred)) 
    print("Classification Report: \n",classification_report (y_test,y_pred))

knn=KNeighborsClassifier(n_neighbors=15)
apply_model(knn)

Model Train Score 0.8579710144927536
Model Test Score 0.8211264201111916
Accuracy 0.8211264201111916
Predictions [0 0 1 ... 0 0 0]
Confusion Matrix: 
 [[2579  367]
 [ 373  818]]
Classification Report: 
               precision    recall  f1-score   support

           0       0.87      0.88      0.87      2946
           1       0.69      0.69      0.69      1191

    accuracy                           0.82      4137
   macro avg       0.78      0.78      0.78      4137
weighted avg       0.82      0.82      0.82      4137



In [19]:
svm = SVC(kernel ='linear',random_state=3,max_iter = 10000)
apply_model(svm)

C:\python\lib\site-packages\sklearn\svm\_base.py:246: ConvergenceWarning: Solver terminated early (max_iter=10000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn('Solver terminated early (max_iter=%i).'


Model Train Score 0.9980676328502416
Model Test Score 0.9199903311578439
Accuracy 0.9199903311578439
Predictions [0 0 0 ... 0 0 1]
Confusion Matrix: 
 [[2722  224]
 [ 107 1084]]
Classification Report: 
               precision    recall  f1-score   support

           0       0.96      0.92      0.94      2946
           1       0.83      0.91      0.87      1191

    accuracy                           0.92      4137
   macro avg       0.90      0.92      0.91      4137
weighted avg       0.92      0.92      0.92      4137



In [20]:
svm = SVC(kernel ='poly',random_state=3,max_iter = 10000)
apply_model(svm)

Model Train Score 0.7555555555555555
Model Test Score 0.7449842881314963
Accuracy 0.7449842881314963
Predictions [0 0 0 ... 0 0 0]
Confusion Matrix: 
 [[2907   39]
 [1016  175]]
Classification Report: 
               precision    recall  f1-score   support

           0       0.74      0.99      0.85      2946
           1       0.82      0.15      0.25      1191

    accuracy                           0.74      4137
   macro avg       0.78      0.57      0.55      4137
weighted avg       0.76      0.74      0.67      4137

